spring:
  application:
    name: RentEase
  data:
    mongodb:
      uri: mongodb+srv://Buddhima:buddhima321@cluster0.wscsft9.mongodb.net/renthome?retryWrites=true&w=majority
      database: renthome

server:
  port: 8081

logging:
  level:
    root: INFO
    com.rentease: DEBUG
    org.mongodb.driver: WARN
