# ========================
# Application
# ========================
spring.application.name=RentEase

# ========================
# MongoDB Atlas
# ========================
# Spring Boot uses spring.data.mongodb.uri
spring.data.mongodb.uri=mongodb+srv://Buddhima:buddhima321@cluster0.wscsft9.mongodb.net/rentease?retryWrites=true&w=majority

# ========================
# Server
# ========================
server.port=8081

# ========================
# Logging
# ========================
logging.level.root=INFO
logging.level.com.rentease=DEBUG
logging.level.org.mongodb.driver=INFO

# ========================
# Email (SMTP)
# ========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hiru.official2004@gmail.com
spring.mail.password=fxzjmmtehbccihnx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
