# ========================
# Application
# ========================
spring.application.name=RentEase

# ========================
# MongoDB Atlas
# ========================
# Spring Boot uses spring.data.mongodb.uri
spring.data.mongodb.uri=mongodb+srv://Buddhima:buddhima321@cluster0.wscsft9.mongodb.net/rentease?retryWrites=true&w=majority

# ========================
# Server
# ========================
server.port=8080

# ========================
# Logging
# ========================
logging.level.root=INFO
logging.level.com.rentease=DEBUG
logging.level.org.mongodb.driver=INFO
